server:
  port: 8090
  servlet:
    context-path: /dna/example
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
